spring.application.name=demo_service

spring.config.import=optional:file:.env[.properties]

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=10c71b6d07daefa7bf5d01b1061299a18def287081f95e59286d9600c62ac434
spring.datasource.password=sk_EjgwkdqzPRl9M56ZTNg_f
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Cambia el nivel global a solo Advertencias y Errores
logging.level.root=WARN



